
export const dataRider = [
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phone: '1234567890',
        password: 'password123',
        profileImage: null,
        citizenId: '1234567890123',
        dob: new Date('1985-05-15'),
        address: '123 Main St, Anytown, USA',
        driverLicense: 'D12345678',
        licensePlate: 'ABC123',
        vehicleImage: null,
        status: 'SUBMITTED',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@example.com',
        phone: '0987654321',
        password: 'password456',
        profileImage: null,
        citizenId: '2345678901234',
        dob: new Date('1990-07-20'),
        address: '456 Oak St, Sometown, USA',
        driverLicense: 'S23456789',
        licensePlate: 'XYZ789',
        vehicleImage: null,
        status: 'APPROVED',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        firstName: 'Alice',
        lastName: 'Johnson',
        email: 'alice.johnson@example.com',
        phone: '5556667777',
        password: 'password789',
        profileImage: null,
        citizenId: '3456789012345',
        dob: new Date('1975-11-25'),
        address: '789 Pine St, Anothertown, USA',
        driverLicense: 'J34567890',
        licensePlate: 'LMN456',
        vehicleImage: null,
        status: 'SUBMITTED',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        firstName: 'Bob',
        lastName: 'Williams',
        email: 'bob.williams@example.com',
        phone: '4445556666',
        password: 'password012',
        profileImage: null,
        citizenId: '4567890123456',
        dob: new Date('1980-03-10'),
        address: '101 Maple St, Sampletown, USA',
        driverLicense: 'W45678901',
        licensePlate: 'OPQ345',
        vehicleImage: null,
        status: 'APPROVED',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        firstName: 'Charlie',
        lastName: 'Brown',
        email: 'charlie.brown@example.com',
        phone: '3334445555',
        password: 'password345',
        profileImage: null,
        citizenId: '5678901234567',
        dob: new Date('1995-12-05'),
        address: '202 Elm St, Exampletown, USA',
        driverLicense: 'B56789012',
        licensePlate: 'RST234',
        vehicleImage: null,
        status: 'CANCELED',
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];
